/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { API } from "./lib/index.js";
export namespace Components {
    interface CbsAutocomplete {
        "fetchAdress": (val: any) => Promise<void>;
        "target": string;
        "value": string;
    }
    interface FibsBooking {
        "API": API;
        "apikey": string;
        "cover": string;
        "height": string;
    }
}
declare global {
    interface HTMLCbsAutocompleteElement extends Components.CbsAutocomplete, HTMLStencilElement {
    }
    var HTMLCbsAutocompleteElement: {
        prototype: HTMLCbsAutocompleteElement;
        new (): HTMLCbsAutocompleteElement;
    };
    interface HTMLFibsBookingElement extends Components.FibsBooking, HTMLStencilElement {
    }
    var HTMLFibsBookingElement: {
        prototype: HTMLFibsBookingElement;
        new (): HTMLFibsBookingElement;
    };
    interface HTMLElementTagNameMap {
        "cbs-autocomplete": HTMLCbsAutocompleteElement;
        "fibs-booking": HTMLFibsBookingElement;
    }
}
declare namespace LocalJSX {
    interface CbsAutocomplete {
        "target"?: string;
        "value": string;
    }
    interface FibsBooking {
        "API"?: API;
        "apikey": string;
        "cover"?: string;
        "height"?: string;
    }
    interface IntrinsicElements {
        "cbs-autocomplete": CbsAutocomplete;
        "fibs-booking": FibsBooking;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "cbs-autocomplete": LocalJSX.CbsAutocomplete & JSXBase.HTMLAttributes<HTMLCbsAutocompleteElement>;
            "fibs-booking": LocalJSX.FibsBooking & JSXBase.HTMLAttributes<HTMLFibsBookingElement>;
        }
    }
}
